version: '1.0'

services:
  ocelotapigw:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    container_name: ocelotapigw
    depends_on:
        - airport.api
    ports:
        - 7000:80

  airport.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    container_name: airport.api
    depends_on:
        - airportinfo.grpc
        - measuring.grpc
    ports:
        - 5200:80
        
  airportinfo.grpc:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    container_name: airportinfo.grpc
    ports:
        - 5101:80

  measuring.grpc:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    container_name: measuring.grpc
    ports:
        - 5102:80

